# Generated by Django 4.1.1 on 2022-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
